name: Action workflow

on:
 push:
 schedule:
    - cron: '0 0 * * *'
 workflow_dispatch:

jobs:
  action_job:
    runs-on: ubuntu-latest
    name: Ritchie Action
    steps:
    - name: Run Ritchie Action Command
      uses: GuillaumeFalourd/ritchie-action-shell@main
      with:
        rit-repo-url: https://github.com/GuillaumeFalourd/formulas-training
        rit-formula-command: rit shell math sum numbers --number_one=1 --number_two=2
        github-token: ${{ secrets.ACCESS_TOKEN }}
